local desk = [[X:\Users\Default\DeskTop\]]
LINK(desk .. [[iSCSI 发起程序.lnk]], [[iscsicpl.exe]], nil, [[ico\iscsicli.ico]])
LINK(desk .. [[此电脑.lnk]], [[%programfiles%\winxshell.exe]], nil, [[ico\winxshell.ico]])
LINK(desk .. [[TightVNC Viewer.lnk]], [[tightvnc\tvnviewer.exe]], nil, nil)
LINK(desk .. [[iSCSI 发起程序.lnk]], [[iscsicpl.exe]], nil, [[ico\iscsicli.ico]])
LINK(desk .. [[ghostx64.lnk]], [[ghostx64.exe]], nil, nil)
LINK(desk .. [[netcopy网络同传.lnk]], [[netcopyx64.exe]], nil, nil)
LINK(desk .. [[CGI一键还原.lnk]], [[cgix64.exe]], nil, nil)
LINK(desk .. [[BT客户端.lnk]], [[btx64.exe]], nil, nil)
LINK(desk .. [[引导修复.lnk]], [[ShowDrives_Gui_x64.exe]], [[--Bcdbootgui]], nil)
LINK(desk .. [[镜像挂载工具.lnk]], [[ShowDrives_Gui_x64.exe]], nil, nil)
LINK(desk .. [[文件共享盘.lnk]], [[explorer.exe]], [[B:\]], nil)
LINK(desk .. [[文件共享盘.lnk]], [[%programfiles%\explorer.exe]], [[B:\]], nil)
LINK(desk .. [[文件共享盘.lnk]], [[%programfiles%\winxshell.exe]], [[B:\]], nil)
LINK(desk .. [[Ghost自动网克.lnk]], [[startup.bat]], [[netghost]], [[ico\ghost32.ico]])
LINK(desk .. [[连接共享.lnk]], [[startup.bat]], [[smbcli]], [[ico\smbcli.ico]])
LINK(desk .. [[多播接收.lnk]], [[startup.bat]], [[cloud]], [[ico\uftpd.ico]])
LINK(desk .. [[多播发送.lnk]], [[uftp.exe]], [[-R 800000]], [[ico\uftp.ico]])
LINK(desk .. [[Hou多播发送.lnk]], [[housx86.exe]], [[E:\system.wim]], [[housx86.exe]])
LINK(desk .. [[Hou多播接收.lnk]], [[houcx86.exe]], [[I:\]], [[houcx86.exe]])
LINK(desk .. [[伽卡教师端.lnk]], [[gakax86.exe]], nil, [[gakax86.exe]])
LINK(desk .. [[伽卡学生端.lnk]], [[gakax86.exe]], [[student]], [[gakax86.exe]])
LINK(desk .. [[DG分区工具.lnk]], [[DiskGeniusx86.exe]], nil, nil)